language: ruby
rvm:
  - jruby-19mode
  - rbx-19mode
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7